---
title: "My CE"
author: "liela"
date: "2/13/2021"
output: html_document
---
```{r setup, include=FALSE,warning=FALSE}
rm(list=ls())
library(readr)
library(tidyverse)
library(dplyr)
data0 <- read_csv("data.csv") %>% mutate(agent=as.factor(agent),studyID=as.factor(studyID),AuthorYear=as.factor(AuthorYear))
library(MBNMAdose)
data_mba <- mbnma.network(data0)
data <- data_mba$data.ab %>% dplyr::select(studyID, treatment, r, N) %>% mutate(treatment=as.factor(treatment))
```

```{r network plots,warning=FALSE}
# treatment level
# quartz()
plot(data_mba, label.distance =2,v.color = "agent") # all vertices/treatments are connected
# agent level
# plot(data_mba,level = "agent",label.distance =5,v.color = "agent") # all agents are connected to the network/placebo
```

```{r netmeta,warning=FALSE}
library(netmeta)
data_w0 <- data0 %>% mutate(tr=paste(agent, dose)) %>% dplyr::select(studyID, N, r, tr) 
data_net <- pairwise(tr, event = r, n = N,studlab = studyID, data = data_w0)
# netma_MH <- netmetabin(data_net, ref="PLA 0", sm=c("OR","RR"),all.treatments = T, backtransf = T)
netma_I <- netmetabin(data_net, ref="PLA 0", sm="RR",all.treatments = T, backtransf = T, method = "Inverse",comb.fixed = F)
# netma_simple <- netmetabin(data_net, ref="PLA 0")
# forest.netmeta(netma) ; forest.netmeta(netma_simple)
forest.netmeta(netma_I)
# netgraph(netma)
netmeta::netrank(netma_I, small.values = "good" )
plot(netrank(netma_I,small.values = "good"))
decomp.design(netma_I)
round(decomp.design(netma_I)$Q.decomp,3)
print(netma_I, digits=2) # considerable heterogeneity
netma_I$TE.nm
# netleague(netma)
#par(mar=c(1,1,1,1))
#netheat(netma_I,cex.axis=0.2,cex.names=0.2,pch=0.2)

fe <- netma_I$TE.nma.fixed
re <- netma_I$TE.nma.random

plot(jitter((fe+re)/2, 5), jitter(fe-re,5))
abline(h=0)
```

```{r pcnetmeta,warning=FALSE}
library(coda)
library(rjags)
library(pcnetmeta)
set.seed(1234)
### network ploting
# nma.networkplot(studyID, treatment,  N,data = data, trtname = data_mba$treatments, weight.node.ss = TRUE, multi.col=seq(1,9,by=1))
### estimation
nma.out <- nma.ab.bin(studyID, treatment, r, N, data = data, trtname = data_mba$treatments,param=c("RR","rank.prob"),higher.better = F, model = "het_cor", n.adapt = 1000, n.iter = 100,postdens = T,conv.diag = T,dic = T,link="logit")
#results
nma.out$AbsoluteRisk  
nma.out$RelativeRisk
# nma.out$TrtRankProb
rank.prob(nma.out)
# absolute plot
absolute.plot(nma.out, save = FALSE)
contrast.plot(nma.out,reference = "Placebo_0" ,save = FALSE)
# ZTZ_1
contrast.plot(nma.out,reference = "ZTN_1" ,save = FALSE)

# model = "hom_eqcor"
nma.out_eqcor <- nma.ab.bin(studyID, treatment, r, N, data = data, trtname =
data_mba$treatments,param=c("RR","rank.prob"),higher.better = F, model = "hom_eqcor", n.adapt = 1000, n.iter = 100,postdens = T,conv.diag = T,dic = T)
nma.out_eqcor $AbsoluteRisk  
nma.out_eqcor $RelativeRisk
contrast.plot(nma.out_eqcor,reference = "Placebo_0" ,save = FALSE)
```

```{r Dose Response,warning=FALSE}
####### library ####### 
library('dosresmeta') 
library('mvtnorm')
library("ellipse") 
library('mvmeta')
library('rms')
library('meta')
library('metafor') 
library('rmeta')
####### data st up - FRN #######
FRN_i <- data_mba$data.ab %>% dplyr::filter(agent == 4)
FRN_1112 <- data_mba$data.ab %>% dplyr::filter(studyID %in% c(11,12))
FRN_c <- FRN_1112  %>% dplyr::filter(dose == 0) %>% mutate(CE=r, CN=N ) %>% dplyr::select(AuthorYear, CE, CN)
FRN_new <- FRN_i %>% left_join(FRN_c,by="AuthorYear")
FRN_rr <- FRN_new %>% group_by(studyID) %>% filter(dose!=0) %>% mutate(logrr = log((r/N)/(CE/CN)), se=sqrt(1/r+1/CE-1/N-1/CN))
FRN_2 <- data_mba$data.ab %>% dplyr::filter(studyID %in% c(11,12)) %>% dplyr::filter(dose == 0) %>% mutate(CE=r, CN=N,logrr=0, se=NA)
FRN <- rbind(FRN_rr,FRN_2 )
data2 <- FRN %>% dplyr::select(studyID,AuthorYear,dose,r,N,logrr,se) %>% mutate(inver_se=1/se, type="cc",type=as.factor(type),studyID=as.integer(studyID))
######## for study 11 & 12  ######## 
ggplot(data2, aes(dose, logrr, size = exp(inver_se*10))) + geom_point ( colour = 'dark grey',show.legend = FALSE) + scale_size_area(max_size = 10) +facet_wrap(~studyID)
ggplot(data2, aes(dose, logrr, size = exp(inver_se*10))) + geom_point ( colour = 'dark grey',show.legend = FALSE) + scale_size_area(max_size = 10)   
# Linear model
lin_bin <- dosresmeta(formula = logrr ~ dose, id = studyID,se = se,type="ir", cases = r, n = N, data = data2)
summary(lin_bin)
predict(lin_bin, delta = 5, exp = TRUE)
# Linear model graph
dosex_bin <- data.frame(dose = seq(0, 50, 1))
with(predict(lin_bin, dosex_bin, order = TRUE, exp = TRUE),
{plot(dose, pred, type = "l", col = "blue", ylim = c(0, 10), ylab =  "predicted relative risk ", xlab = "dose of agonist - FRN")
lines(dose, ci.lb, lty = 2)
lines(dose, ci.ub, lty = 2)})
# 11
data_new <- data2 %>% dplyr::filter(studyID==11)
lin_bin1 <- dosresmeta(formula = logrr ~ dose, id = studyID, se = se,type="ir", cases = r, n = N, data = data_new)
summary(lin_bin1) # 0.0243 
predict(lin_bin1, delta = 10, exp = TRUE)  # 1.275013	1.083611	1.500222
# 12
data_new2 <- data2 %>% dplyr::filter(studyID==12)
lin_bin2 <- dosresmeta(formula = logrr ~ dose, id = studyID, se = se,type="ir", cases = r, n = N, data = data_new2)
summary(lin_bin2) #  0.1581  
predict(lin_bin2, delta = 10, exp = TRUE) # 4.861056	0.2165831	109.103

```


