*********************
Import data
*********************;
LIBNAME project2 "/folders/myfolders/BST222/project2"; 

proc import datafile="/folders/myfolders/BST222/project2/data0.csv" 
out=project2.data0 dbms=csv;
getnames=yes;
run;

data project2.data;
set project2.data0;
     if stage=1 then do; stage1=1; stage2=0; stage3=0; stage4=0; end;
else if stage=2 then do; stage1=0; stage2=1; stage3=0; stage4=0; end;
else if stage=3 then do; stage1=0; stage2=0; stage3=1; stage4=0; end;
else if stage=4 then do; stage1=0; stage2=0; stage3=0; stage4=1; end;
format F_history F_history. Stage Stage. Metastasis Metastasis. Pathology Pathology. Surgery Surgery.;
run;

Proc format;
 Value F_history
  0 = 'No'
  1 = 'Yes';
  Value Stage
  1 = 'I'
  2 = 'II'
  3 = 'III'
  4 = 'IV';
  Value Metastasis
  0 = 'No'
  1 = 'Yes';
  Value Pathology
  0 = 'IDC'
  1 = 'DCIS';
  Value Surgery
  0 = 'radical mastectomy'
  1 = 'breast saving';
Run; 
******************
Analysis
******************;
proc lifetest data=project2.data plots=survival(atrisk cb);
time time*censored(1);
run;
* table 1;
proc freq data=project2.data;
tables surgery*(metastasis stage pathology f_history)/chisq nocol ;
format f_history f_history. stage stage. pathology pathology. metastasis metastasis. surgery surgery.;
run;
proc sort data=project2.data;
by surgery;
run;
proc univariate data=project2.data;
var age tumor_size;
by surgery;
format surgery surgery.;
run; 
proc ttest data=project2.data;
var age tumor_size;
class surgery;
format surgery surgery.;
run; 
****************
non parametric
****************;
* KM;
proc lifetest data=project2.data plots=survival(atrisk cb cl);
time time*censored(1);
format surgery surgery.;
run;
* hazard rate;
proc lifetest data=project2.data plots=hazard notable;
time time*censored(1);
format surgery surgery.;
run;
****************
surgery type
****************;
* KM;
proc lifetest data=project2.data plots=survival(atrisk cb cl);
time time*censored(1);
strata surgery;
format surgery surgery.;
run;
* hazard rate;
proc lifetest data=project2.data plots=hazard notable;
time time*censored(1);
strata surgery;
format surgery surgery.;
run;
* two sample test;
proc lifetest data=project2.data notable;
time time*censored(1);
strata surgery/test=(wilcoxon fleming(1,0)logrank);
format surgery surgery.;
run;
****************
model building
****************;
proc phreg data=project2.data;
class surgery;
model time*censored(1)= surgery age;
format surgery surgery. ;
run;
proc phreg data=project2.data;
class surgery;
model time*censored(1)= surgery tumor_size;
format surgery surgery. ;
run;
proc phreg data=project2.data;
class surgery f_history;
model time*censored(1)= surgery f_history;
format surgery surgery. f_history f_history.;
run;
proc phreg data=project2.data;
class surgery stage;
model time*censored(1)= surgery stage;
format surgery surgery. stage stage.;
run;
proc phreg data=project2.data;
class surgery metastasis;
model time*censored(1)= surgery metastasis;
format surgery surgery. metastasis metastasis.;
run;
proc phreg data=project2.data;
class surgery pathology;
model time*censored(1)= surgery pathology;
format surgery surgery. pathology pathology.;
run;
* +metastasis;
proc phreg data=project2.data;
class surgery metastasis;
model time*censored(1)= surgery  metastasis age;
format surgery surgery. metastasis metastasis.;
run;
proc phreg data=project2.data;
class surgery;
model time*censored(1)= surgery metastasis tumor_size;
format surgery surgery. ;
run;
proc phreg data=project2.data;
class surgery f_history;
model time*censored(1)= surgery metastasis f_history;
format surgery surgery. f_history f_history.;
run;
proc phreg data=project2.data;
class surgery stage;
model time*censored(1)= surgery metastasis stage;
format surgery surgery. stage stage.;
run;
proc phreg data=project2.data;
class surgery pathology;
model time*censored(1)= surgery metastasis pathology;
format surgery surgery. pathology pathology.;
run;
* + metastasis;
proc phreg data=project2.data;
class surgery metastasis;
model time*censored(1)= surgery  metastasis tumor_size age;
format surgery surgery. metastasis metastasis.;
run;
proc phreg data=project2.data;
class surgery f_history;
model time*censored(1)= surgery metastasis tumor_size f_history;
format surgery surgery. f_history f_history.;
run;
proc phreg data=project2.data;
class surgery stage;
model time*censored(1)= surgery metastasis tumor_size stage;
format surgery surgery. stage stage.;
run;
proc phreg data=project2.data;
class surgery pathology;
model time*censored(1)= surgery metastasis tumor_size pathology;
format surgery surgery. pathology pathology.;
run;
*final model;
proc phreg data=project2.data;
class surgery metastasis;
model time*censored(1)= surgery metastasis tumor_size age;
format surgery surgery. metastasis metastasis.;
run;
************************
Local test- interaction
************************;
*surgery;
proc phreg data=project2.data;
class surgery;
model time*censored(1)= surgery age age*surgery;
contrast "beta3=0" surgery*age 1 /test(wald lr score);
format surgery surgery. ;
run;
proc phreg data=project2.data;
class surgery;
model time*censored(1)= surgery tumor_size tumor_size*surgery;
contrast "beta3=0" surgery*tumor_size 1 /test(wald lr score);
format surgery surgery. ;
run;
proc phreg data=project2.data;
class surgery metastasis;
model time*censored(1)= surgery metastasis metastasis*surgery;
contrast "beta3=0" surgery*metastasis 1 /test(wald lr score);
format surgery surgery. ;
run;
*metastasis;
proc phreg data=project2.data;
class  metastasis;
model time*censored(1)= tumor_size metastasis metastasis*tumor_size;
contrast "beta3=0" tumor_size*metastasis 1 /test(wald lr score);
run;
proc phreg data=project2.data;
class metastasis;
model time*censored(1)= age metastasis metastasis*age;
contrast "beta3=0" age*metastasis 1 /test(wald lr score);
format surgery surgery. ;
run;
*age;
proc phreg data=project2.data;
model time*censored(1)= tumor_size age age*tumor_size;
contrast "beta3=0" tumor_size*age 1 /test(wald lr score);
run;
****************
Cox PH
****************;
proc phreg data=project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= surgery metastasis tumor_size age;
format  Metastasis Metastasis.  Surgery Surgery.;
run;
******* martingale;
* age;
proc phreg data=project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= surgery metastasis tumor_size;
format  Metastasis Metastasis.  Surgery Surgery.;
output out=plot2_1 RESMART = mgale ;
run;
proc loess data=plot2_1; 
  model mgale = age /  direct;
run;
* tumor size;
proc phreg data=project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= surgery metastasis age;
format  Metastasis Metastasis.  Surgery Surgery.;
output out=plot2_1 RESMART = mgale ;
run;
proc loess data=plot2_1; 
  model mgale = tumor_size  /  direct;
run;
************************
PH assumption
************************;
*****************age;
* shoenfeld;
proc phreg data = project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= age surgery metastasis tumor_size ;
format  Metastasis Metastasis.  Surgery Surgery.;
output out = schoen ressch= schage ;
run;
proc loess data=schoen;
model schage=time;
run;
* test;
proc phreg data = project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= age surgery metastasis tumor_size age*time;
format  Metastasis Metastasis.  Surgery Surgery.;
run;
*****************tumorsize;
* shoenfeld;
proc phreg data = project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= tumor_size age surgery metastasis;
format  Metastasis Metastasis.  Surgery Surgery.;
output out = schoen ressch= schsize ;
run;
proc loess data=schoen;
model schsize=time;
run;
*test;
proc phreg data = project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= tumor_size age surgery metastasis tumor_size*time ;
format  Metastasis Metastasis.  Surgery Surgery.;
run;
***************** surgery;
* log(H) vs time;
data new ;
  set project2.data ;
  cons = 1;
run;
proc phreg data = new;
class surgery/param=ref;
 model time*censored(1) =cons/rl ; 
 strata surgery;
 output out = base logsurv = ls /method = ch;
run;  
data base;
  set base ;
    logH = log (-ls);
	if surgery= 0 then logH1 = logH;
    else if surgery= 1 then logH2 = logH;
    proc sort; by surgery time  ;
    proc print; var surgery time logH logH1 logH2 ;
run;
proc sgplot data =base;
where logH ne .;
series x=time y=logH /group=surgery ;
format surgery surgery.;
run;
***************** matastasis;
* log(H) vs time;
data new ;
  set project2.data ;
  cons = 1;
run;
proc phreg data = new;
class metastasis/param=ref;
 model time*censored(1) =cons/rl ; 
 strata metastasis;
 output out = base logsurv = ls /method = ch;
run;  
data base;
  set base ;
    logH = log (-ls);
	if metastasis= 0 then logH1 = logH;
    else if metastasis= 1 then logH2 = logH;
    proc sort; by metastasis time  ;
    proc print; var metastasis time logH logH1 logH2 ;
run;
proc sgplot data =base;
where logH ne .;
series x=time y=logH /group=metastasis ;
format metastasis metastasis.;
run;
*********snell;
proc phreg data=project2.data;
class metastasis surgery(ref="radical mastectomy");
model time*censored(1)= tumor_size age surgery metastasis;
format  Metastasis Metastasis.  Surgery Surgery.;
output out=plot1_1 logsurv = logsurv1/method=ch;
run;
data plot1_1;
  set plot1_1;
  snell = -logsurv1;
  cons = 1;
run;
proc phreg data = plot1_1;
  model  snell*censored(1) = cons;
  output out = plot1_2 logsurv = logsurv2 /method = ch;
run;
data plot1_2;
  set plot1_2;
    cumhaz = - logsurv2;
run;
proc sort data = plot1_2;
 by snell;
run;
proc sgplot data = plot1_2;
step y=cumhaz x=snell /MARKERFILLATTRS=(color="red");
lineparm x=0 y=0 slope=1; /** intercept, slope **/
  label cumhaz = "Estimated Cumulative Hazard Rates";
  label snell = "Residual";
run;
*********snell;
proc phreg data=project2.data;
class metastasis  surgery(ref="radical mastectomy");
model time*censored(1)= tumor_size age surgery;
strata metastasis;
format  Metastasis Metastasis.  Surgery Surgery.;
output out=plot1_1 logsurv = logsurv1/method=ch;
run;
data plot1_1;
  set plot1_1;
  snell = -logsurv1;
  cons = 1;
run;
proc phreg data = plot1_1;
  model  snell*censored(1) = cons;
  output out = plot1_2 logsurv = logsurv2 /method = ch;
run;
data plot1_2;
  set plot1_2;
    cumhaz = - logsurv2;
run;
proc sort data = plot1_2;
 by snell;
run;
proc sgplot data = plot1_2;
step y=cumhaz x=snell /MARKERFILLATTRS=(color="red");
lineparm x=0 y=0 slope=1; /** intercept, slope **/
  label cumhaz = "Estimated Cumulative Hazard Rates";
  label snell = "Residual";
run;
************************
no interacton assumption
************************;
proc phreg data=project2.data;
class metastasis surgery(ref="radical mastectomy");
model time*censored(1)= tumor_size age surgery /rl;
strata metastasis;
format  Metastasis Metastasis.  Surgery Surgery.;
run;
proc phreg data=project2.data;
where metastasis=0;
class metastasis surgery(ref="radical mastectomy");
model time*censored(1)= tumor_size age surgery ;
format  Metastasis Metastasis.  Surgery Surgery.;
run;
proc phreg data=project2.data;
where metastasis=1;
class metastasis surgery(ref="radical mastectomy");
model time*censored(1)= tumor_size age surgery ;
format  Metastasis Metastasis.  Surgery Surgery.;
run;
